name: Build and Release Mod

on:
  push:
    tags:
      - 'v*'  # release on tag push like v1.0.0
  workflow_dispatch:  # manual trigger

permissions:
  contents: write  # needed to create releases

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build project (including shadowJar)
      run: ./gradlew shadowJar

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: build/libs/*.jar
        tag_name: ${{ github.ref_name != '' && startsWith(github.ref_name, 'v') && github.ref_name || 'manual-' + github.run_number }}
        release_name: ${{ github.ref_name != '' && startsWith(github.ref_name, 'v') && github.ref_name || 'Manual Release #' + github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
